# CruzYValencia-Ecommerce/deployment/render.yaml
services:
  - name: cruz-y-valencia-backend
    type: web
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    plan: free
    envVars:
      - key: MONGO_URI
        fromSecret: mongo_uri
      - key: JWT_SECRET
        fromSecret: jwt_secret
      - key: EMAIL_USERNAME
        fromSecret: email_username
      - key: EMAIL_PASSWORD
        fromSecret: email_password
      - key: EMAIL_FROM
        fromSecret: email_from
      - key: PORT
        value: "5000"